In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("media_campaign_data.csv")
df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,College Students,6/4/2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,College Students,4/6/2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Tier 2 City Customers,29-12-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,NY-CMP-1194,Influencer,Premium Shoppers,7,"Email, Instagram",99006,13901,5326,2649,1491387,22.58,23.93,Premium Shoppers,27-05-2025
195,NY-CMP-1195,Influencer,College Students,9,Google,16548,1532,717,505,111100,231.54,-0.05,Tier 2 City Customers,22-02-2025
196,NY-CMP-1196,SEO,College Students,16,Facebook,82471,5797,3251,1940,1369640,101.63,5.95,Tier 2 City Customers,30-05-2025
197,NY-CMP-1197,Social Media,Premium Shoppers,13,"Email, Google, WhatsApp",74621,4124,1052,353,110489,414.62,-0.25,Youth,29-08-2024
198,NY-CMP-1198,Paid Ads,Premium Shoppers,12,"Google, Instagram",60166,7720,3135,1375,723250,184.29,1.85,Youth,16-03-2025

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       199 non-null    object
 1   Campaign_Type     199 non-null    object
 2   Target_Audience   199 non-null    object
 3   Duration          199 non-null    int64
 4   Channel_Used      199 non-null    object
 5   Impressions       199 non-null    int64
 6   Clicks            199 non-null    int64
 7   Leads             199 non-null    int64
 8   Conversions       199 non-null    int64
 9   Revenue           199 non-null    int64
 10  Acquisition_Cost  199 non-null    float64
 11  ROI               199 non-null    float64
 12  Customer_Segment  199 non-null    object
 13  Date              199 non-null    object
dtypes: float64(2), int64(6), object(6)
memory usage: 21.9+ KB

In [ ]:
df.dtypes

Campaign_ID          object
Campaign_Type        object
Target_Audience      object
Duration              int64
Channel_Used         object
Impressions           int64
Clicks                int64
Leads                 int64
Conversions           int64
Revenue               int64
Acquisition_Cost    float64
ROI                 float64
Customer_Segment     object
Date                 object
dtype: object

In [ ]:
df.isna().sum()

Campaign_ID         0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Impressions         0
Clicks              0
Leads               0
Conversions         0
Revenue             0
Acquisition_Cost    0
ROI                 0
Customer_Segment    0
Date                0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Date"] = pd.to_datetime(
    df["Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [ ]:
df["Date"] = (
    df["Date"]
    .astype(str)
    .str.strip()
)

df["Date"] = pd.to_datetime(
    df["Date"],
    errors="coerce"
)

In [ ]:
df['Date']

0     2025-04-29
1     2025-04-06
2     2025-01-14
3     2025-06-04
4     2024-12-29
         ...
194   2025-05-27
195   2025-02-22
196   2025-05-30
197   2024-08-29
198   2025-03-16
Name: Date, Length: 199, dtype: datetime64[ns]

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       199 non-null    object
 1   Campaign_Type     199 non-null    object
 2   Target_Audience   199 non-null    object
 3   Duration          199 non-null    int64
 4   Channel_Used      199 non-null    object
 5   Impressions       199 non-null    int64
 6   Clicks            199 non-null    int64
 7   Leads             199 non-null    int64
 8   Conversions       199 non-null    int64
 9   Revenue           199 non-null    int64
 10  Acquisition_Cost  199 non-null    float64
 11  ROI               199 non-null    float64
 12  Customer_Segment  199 non-null    object
 13  Date              199 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(6), object(5)
memory usage: 21.9+ KB
None

In [ ]:
df = df.fillna(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
print(df.shape)

(199, 14)

In [ ]:
pd.to_datetime(df["Date"], format="%d-%m-%Y")

0     2025-04-29
1     2025-04-06
2     2025-01-14
3     2025-06-04
4     2024-12-29
         ...
194   2025-05-27
195   2025-02-22
196   2025-05-30
197   2024-08-29
198   2025-03-16
Name: Date, Length: 199, dtype: datetime64[ns]

In [ ]:
df
df.to_csv("cleaned_media_data.csv", index=False)

In [ ]:
df

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,College Students,2025-04-29
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,College Students,2025-04-06
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,College Students,2025-01-14
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,College Students,2025-06-04
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Tier 2 City Customers,2024-12-29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,NY-CMP-1194,Influencer,Premium Shoppers,7,"Email, Instagram",99006,13901,5326,2649,1491387,22.58,23.93,Premium Shoppers,2025-05-27
195,NY-CMP-1195,Influencer,College Students,9,Google,16548,1532,717,505,111100,231.54,-0.05,Tier 2 City Customers,2025-02-22
196,NY-CMP-1196,SEO,College Students,16,Facebook,82471,5797,3251,1940,1369640,101.63,5.95,Tier 2 City Customers,2025-05-30
197,NY-CMP-1197,Social Media,Premium Shoppers,13,"Email, Google, WhatsApp",74621,4124,1052,353,110489,414.62,-0.25,Youth,2024-08-29
198,NY-CMP-1198,Paid Ads,Premium Shoppers,12,"Google, Instagram",60166,7720,3135,1375,723250,184.29,1.85,Youth,2025-03-16